name: hisab_pro_final
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  google_sign_in: ^6.2.1
  lottie: ^2.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.3.3
  fl_chart: ^0.65.0
  permission_handler: ^11.0.0
  speech_to_text: ^6.3.0
  pdf: ^3.10.6
  printing: ^5.9.0
  path_provider: ^2.1.1
  flutter_local_notifications: ^16.1.0
  flutter_tts: ^4.0.2
  image_picker: ^1.0.7
  google_mlkit_text_recognition: ^0.10.0
  csv: ^5.0.2
  share_plus: ^7.0.2
  local_auth: ^2.1.6
  shared_preferences: ^2.2.2
  pin_code_fields: ^8.0.1
  flutter_secure_storage: ^8.0.0
  encrypt: ^5.0.1
  file_picker: ^8.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png
    - assets/money_anim.json
    - assets/loading_anim.json
    - assets/404_anim.json
    - assets/success_anim.json 
